// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utah_Project_API.Data;

#nullable disable

namespace Utah_Project_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214224013_RenameTraitsToMutations")]
    partial class RenameTraitsToMutations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Utah_Project_API.Models.Behaviour_Lib", b =>
                {
                    b.Property<string>("behaviourCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("behaviourDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("behaviourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("behaviourCode");

                    b.ToTable("Behaviours");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Behaviour", b =>
                {
                    b.Property<int>("dinoCode")
                        .HasColumnType("int");

                    b.Property<string>("behaviourCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("dinoCode", "behaviourCode");

                    b.HasIndex("behaviourCode");

                    b.ToTable("DinoBehaviours");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Mutation", b =>
                {
                    b.Property<int>("dinoCode")
                        .HasColumnType("int");

                    b.Property<string>("mutationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mutationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dinoCode", "mutationCode");

                    b.HasIndex("mutationCode");

                    b.ToTable("DinoTraits");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Nesting", b =>
                {
                    b.Property<int>("dinoCode")
                        .HasColumnType("int");

                    b.Property<int>("nestingId")
                        .HasColumnType("int");

                    b.HasKey("dinoCode", "nestingId");

                    b.HasIndex("nestingId");

                    b.ToTable("DinoNestings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Relationship", b =>
                {
                    b.Property<int>("dinocode")
                        .HasColumnType("int");

                    b.Property<int>("targetDinocode")
                        .HasColumnType("int");

                    b.Property<int>("relationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("customBondLabel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dinocode", "targetDinocode", "relationTypeId");

                    b.HasIndex("relationTypeId");

                    b.HasIndex("targetDinocode");

                    b.ToTable("DinoRelationships");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.Property<int>("dinoCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dinoCode"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dinoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nestId")
                        .HasColumnType("int");

                    b.Property<int>("speciesId")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("dinoCode");

                    b.HasIndex("nestId");

                    b.HasIndex("speciesId");

                    b.HasIndex("userId");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Mutation_Lib", b =>
                {
                    b.Property<string>("mutationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mutationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mutationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mutationCode");

                    b.ToTable("Mutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.Property<int>("nestingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nestingId"));

                    b.Property<string>("extendedDesciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nestingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parent1Id")
                        .HasColumnType("int");

                    b.Property<int?>("parent2Id")
                        .HasColumnType("int");

                    b.HasKey("nestingId");

                    b.HasIndex("parent1Id");

                    b.HasIndex("parent2Id");

                    b.ToTable("Nestings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Mutation", b =>
                {
                    b.Property<int>("nestingId")
                        .HasColumnType("int");

                    b.Property<string>("mutationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("mutationChance")
                        .HasColumnType("real");

                    b.Property<string>("mutationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nestingId", "mutationCode");

                    b.HasIndex("mutationCode");

                    b.ToTable("NestingMutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Relation_Type", b =>
                {
                    b.Property<int>("relationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("relationTypeId"));

                    b.Property<int>("RelationTypes")
                        .HasColumnType("int");

                    b.HasKey("relationTypeId");

                    b.ToTable("RelationTypes");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Species", b =>
                {
                    b.Property<int>("speciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("speciesId"));

                    b.Property<string>("speciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("speciesId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Utah_Project_API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Behaviour", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Behaviour_Lib", "Behaviour")
                        .WithMany()
                        .HasForeignKey("behaviourCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "dinosaur")
                        .WithMany("dinoBehaviours")
                        .HasForeignKey("dinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Behaviour");

                    b.Navigation("dinosaur");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Mutation", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "dinosaur")
                        .WithMany("dinoMutations")
                        .HasForeignKey("dinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Mutation_Lib", "Mutation")
                        .WithMany("dino_Mutations")
                        .HasForeignKey("mutationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mutation");

                    b.Navigation("dinosaur");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Nesting", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dinosaur")
                        .WithMany()
                        .HasForeignKey("dinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "nesting")
                        .WithMany()
                        .HasForeignKey("nestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dinosaur");

                    b.Navigation("nesting");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Relationship", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dino")
                        .WithMany("dinoRelationships")
                        .HasForeignKey("dinocode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Relation_Type", "relationType")
                        .WithMany()
                        .HasForeignKey("relationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "TargetDino")
                        .WithMany()
                        .HasForeignKey("targetDinocode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dino");

                    b.Navigation("TargetDino");

                    b.Navigation("relationType");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "nest")
                        .WithMany("offsprings")
                        .HasForeignKey("nestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Utah_Project_API.Models.Species", "species")
                        .WithMany()
                        .HasForeignKey("speciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.User", "user")
                        .WithMany("OwnedDinosaurs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nest");

                    b.Navigation("species");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "parent1")
                        .WithMany("nestingsAsParent1")
                        .HasForeignKey("parent1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "parent2")
                        .WithMany("nestingsAsParent2")
                        .HasForeignKey("parent2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("parent1");

                    b.Navigation("parent2");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Mutation", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Mutation_Lib", "Mutation")
                        .WithMany()
                        .HasForeignKey("mutationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "nesting")
                        .WithMany()
                        .HasForeignKey("nestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mutation");

                    b.Navigation("nesting");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.Navigation("dinoBehaviours");

                    b.Navigation("dinoMutations");

                    b.Navigation("dinoRelationships");

                    b.Navigation("nestingsAsParent1");

                    b.Navigation("nestingsAsParent2");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Mutation_Lib", b =>
                {
                    b.Navigation("dino_Mutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.Navigation("offsprings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.User", b =>
                {
                    b.Navigation("OwnedDinosaurs");
                });
#pragma warning restore 612, 618
        }
    }
}
