// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Utah_Project_API.Data;

#nullable disable

namespace Utah_Project_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610191258_InitialMigrationToPostgres")]
    partial class InitialMigrationToPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Utah_Project_API.Models.Behaviour_Lib", b =>
                {
                    b.Property<string>("BehaviourCode")
                        .HasColumnType("text");

                    b.Property<string>("BehaviourDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BehaviourName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BehaviourCode");

                    b.ToTable("Behaviours");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Behaviour", b =>
                {
                    b.Property<int>("DinoCode")
                        .HasColumnType("integer");

                    b.Property<string>("BehaviourCode")
                        .HasColumnType("text");

                    b.HasKey("DinoCode", "BehaviourCode");

                    b.HasIndex("BehaviourCode");

                    b.ToTable("DinoBehaviours");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Mutation", b =>
                {
                    b.Property<int>("DinoCode")
                        .HasColumnType("integer");

                    b.Property<string>("MutationCode")
                        .HasColumnType("text");

                    b.HasKey("DinoCode", "MutationCode");

                    b.HasIndex("MutationCode");

                    b.ToTable("DinoMutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Nesting", b =>
                {
                    b.Property<int>("DinoCode")
                        .HasColumnType("integer");

                    b.Property<int>("NestingId")
                        .HasColumnType("integer");

                    b.HasKey("DinoCode", "NestingId");

                    b.HasIndex("NestingId");

                    b.ToTable("DinoNestings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Relationship", b =>
                {
                    b.Property<int>("DinoCode")
                        .HasColumnType("integer");

                    b.Property<int>("TargetDinoCode")
                        .HasColumnType("integer");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomBondLabel")
                        .HasColumnType("text");

                    b.HasKey("DinoCode", "TargetDinoCode", "RelationTypeId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("TargetDinoCode");

                    b.ToTable("DinoRelationships");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.Property<int>("DinoCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DinoCode"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DinoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int?>("NestId")
                        .HasColumnType("integer");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DinoCode");

                    b.HasIndex("NestId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Mutation_Lib", b =>
                {
                    b.Property<string>("MutationCode")
                        .HasColumnType("text");

                    b.Property<string>("MutationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MutationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MutationCode");

                    b.ToTable("Mutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.Property<int>("NestingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NestingId"));

                    b.Property<string>("ExtendedDesciption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NestingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Parent1Code")
                        .HasColumnType("integer");

                    b.Property<int?>("Parent2Code")
                        .HasColumnType("integer");

                    b.HasKey("NestingId");

                    b.HasIndex("Parent1Code");

                    b.HasIndex("Parent2Code");

                    b.ToTable("Nestings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Mutation", b =>
                {
                    b.Property<int>("NestingId")
                        .HasColumnType("integer");

                    b.Property<string>("MutationCode")
                        .HasColumnType("text");

                    b.Property<float>("MutationChance")
                        .HasColumnType("real");

                    b.Property<string>("MutationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NestingId", "MutationCode");

                    b.HasIndex("MutationCode");

                    b.ToTable("NestingMutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Relation_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RelationTypes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RelationTypes");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<string>("SpeciesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Utah_Project_API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Utah_Project_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Behaviour", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Behaviour_Lib", "Behaviour")
                        .WithMany()
                        .HasForeignKey("BehaviourCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dinosaur")
                        .WithMany("DinoBehaviours")
                        .HasForeignKey("DinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Behaviour");

                    b.Navigation("Dinosaur");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Mutation", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dinosaur")
                        .WithMany("DinoMutations")
                        .HasForeignKey("DinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Mutation_Lib", "Mutation")
                        .WithMany("DinoMutations")
                        .HasForeignKey("MutationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dinosaur");

                    b.Navigation("Mutation");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Nesting", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dinosaur")
                        .WithMany()
                        .HasForeignKey("DinoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "Nesting")
                        .WithMany()
                        .HasForeignKey("NestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dinosaur");

                    b.Navigation("Nesting");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dino_Relationship", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Dino")
                        .WithMany("DinoRelationships")
                        .HasForeignKey("DinoCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Relation_Type", "RelationType")
                        .WithMany()
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "TargetDino")
                        .WithMany()
                        .HasForeignKey("TargetDinoCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dino");

                    b.Navigation("RelationType");

                    b.Navigation("TargetDino");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "Nest")
                        .WithMany("Offsprings")
                        .HasForeignKey("NestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Utah_Project_API.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.User", "User")
                        .WithMany("OwnedDinosaurs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nest");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Parent1")
                        .WithMany("NestingsAsParent1")
                        .HasForeignKey("Parent1Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Utah_Project_API.Models.Dinosaur.Dinosaur", "Parent2")
                        .WithMany("NestingsAsParent2")
                        .HasForeignKey("Parent2Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent1");

                    b.Navigation("Parent2");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Mutation", b =>
                {
                    b.HasOne("Utah_Project_API.Models.Mutation_Lib", "Mutation")
                        .WithMany()
                        .HasForeignKey("MutationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utah_Project_API.Models.Nesting_Lib", "Nesting")
                        .WithMany()
                        .HasForeignKey("NestingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mutation");

                    b.Navigation("Nesting");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Dinosaur.Dinosaur", b =>
                {
                    b.Navigation("DinoBehaviours");

                    b.Navigation("DinoMutations");

                    b.Navigation("DinoRelationships");

                    b.Navigation("NestingsAsParent1");

                    b.Navigation("NestingsAsParent2");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Mutation_Lib", b =>
                {
                    b.Navigation("DinoMutations");
                });

            modelBuilder.Entity("Utah_Project_API.Models.Nesting_Lib", b =>
                {
                    b.Navigation("Offsprings");
                });

            modelBuilder.Entity("Utah_Project_API.Models.User", b =>
                {
                    b.Navigation("OwnedDinosaurs");
                });
#pragma warning restore 612, 618
        }
    }
}
